name: checkouttest into main

on:
 workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
      - name: checkout into different repo
        uses: actions/checkout@v3
        with: 
         repository: bishtraja/new.git
         ref: new
       
