name: Trigger jenkins job

on:
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check if curl is installed
        run: |
          if ! command -v curl &> /dev/null
          then
              echo "curl is not installed"
              exit 1
          else
              echo "curl is installed"
          fi
      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl


  trigger-a-jenkins-job:
    runs-on: ubuntu-latest
    steps:
      - id: triggerjenkinsjob
        uses: mickeygoussetorg/trigger-jenkins-job@v1
        with:
          jenkins-server:  "${{ secrets.JENKINS_SERVER }}" 
          jenkins-job: "test" 
          jenkins-username: ${{ secrets.JENKINS_USERNAME }} 
          jenkins-pat: ${{ secrets.JENKINS_PAT }} 
          poll-time: 10 
          timeout-value: 600 
          verbose: true

