name: Deploy
on:
 workflow_dispatch:
jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm list
          kubeconfig: '${{ secrets.KUBECONFIG }}'
