name: Kubectl Action

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check kubectl version
        run: kubectl version --client
        
      - name: upgrade kubectl version  
        run: |
          curl -LO "https://dl.k8s.io/release/v1.23.6/bin/darwin/arm64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin
          kubectl version --client
          
      - uses: actions/checkout@v1
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods
