name: Merge test into main

on:
 workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Merge test -> main
        uses: devmasx/merge-branch@master
        env:
          MY_TOKEN: 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
        with:
          type: now
          from_branch: test
          target_branch: main
          github_token: ${{ MY_TOKEN }}
