name: Test
on:
 push:
    branches: [ "test" ]

jobs:
  merge-branch:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@main

      - name: Merge test -> prod
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: test
          target_branch: prod
          github_token: ${{ secrets.MY_TOKEN }}
